title: Singam.org
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  This description appears in the document head meta (for
#  Google search results) and in the feed.xml site description.
# baseurl: "/" # the subpath of the site, e.g. /blog
url: "https://www.singam.org" #base URL
#twitter_username: user
#github_username:  user


# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
minima:
  skin: solarized-light

plugins:
  - jekyll-feed