title: Singam.org
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  This description appears in the document head meta (for
#  Google search results) and in the feed.xml site description.
# baseurl: "/" # the subpath of the site, e.g. /blog
url: "https://www.singam.org" #base URL
#twitter_username: user
#github_username:  user

# clicky: 101447765
# sc_project: 12981129
# sc_security: a356a11d

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
